name: MOSAIC NES CI
on: [push]

jobs:
  mosaic-nes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install SUMO
        run: |
          sudo apt-get update
          sudo apt-get install -y --allow-unauthenticated software-properties-common
          sudo add-apt-repository ppa:sumo/stable
          sudo apt-get install -y sumo
      - name: Build NES Java Client
        working-directory: ./libs/nebulastream-java-client
        run: ./gradlew install
      - name: Build MOSAIC NES Applications
        run: mvn clean install
      - name: MOSAIC Integration Tests
        run: |
          docker pull paguos/nes-ui:v0.0.1
          docker pull paguos/nes-mobility:0.0.2
          mvn test -fae -P integration-tests
  tool-scenario-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.17.2'
      - name: Install SUMO
        run: |
          sudo apt-get update
          sudo apt-get install -y --allow-unauthenticated software-properties-common
          sudo add-apt-repository ppa:sumo/stable
          sudo apt-get install -y sumo
      - name: Build
        working-directory: ./tools/scenario-generator
        run: make build-cmake
      - name: Run tests
        working-directory: ./tools/scenario-generator
        run: make tests
      - name: Run integration test
        working-directory: ./tools/scenario-generator
        run: make integration-test
